name: lab-ztp-nightly
on:
  schedule:
    - cron: '31 2 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 PLAN: lab
 INPUTFILE: plans/kcli_plan_ztp.yml
 PARAMFILE: paramfiles/lab_ztp_ipv6.yml
 PULLSECRET: /root/openshift_pull.json

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v3
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-plan:
      needs: requirements
      runs-on: libvirt
      steps:
        - name: Deploy kcli plan
          run: |
            # temp fix
            echo "  "ignitionConfigOverride: \'{\"ignition\":{\"version\":\"3.1.0\"}\,\"storage\":{\"files\":[{\"overwrite\":true\,\"path\":\"/etc/containers/policy.json\"\,\"mode\":755\,\"user\":{\"name\":\"root\"}\,\"contents\":{\"source\":\"data:\,%7B%22default%22%3A%5B%7B%22type%22%3A%22insecureAcceptAnything%22%7D%5D%2C%22transports%22%3A%7B%22docker-daemon%22%3A%7B%22%22%3A%5B%7B%22type%22%3A%22insecureAcceptAnything%22%7D%5D%7D%7D%7D\"}}]}}\' >> ztp/scripts/spoke.sample.yml
            kcli -C local create plan --force -f $INPUTFILE --paramfile $PARAMFILE -P pullsecret=$PULLSECRET $PLAN
